spring:
  datasource:
    url: jdbc:h2:~/stockbatchdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: /Users/fabiomiyasato/Documents/stockbatch.txt
  chunk: cadastro_pessoa.txt