server:
  port: 8081

fiap:
  debug: true

spring:
  datasource:
    url: jdbc:h2:~/fiapstockdatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    show-sql: true

jwt:
  secret: f1aPs3cr37
  expire: 5